# Generated by Django 4.1.7 on 2023-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('objects_detected', models.CharField(max_length=255)),
                ('timestamp', models.DateField()),
            ],
            options={
                'db_table': 'InfoModel',
            },
        ),
    ]
